services:
  web:
    build:
      context: .
    ports:
    - 8000:5000
    volumes:
    - ./:/simple_app

  mysqldb:
    image: mysql
    ports:
    - 3306:3306
    volumes:
    - mysql:/var/lib/mysql
    - mysql_config:/etc/mysql
    env_file:
    - .env

volumes:
  mysql:
  mysql_config: